### ISSUE TITLE
crass : [ERROR] Could not open FASTQ <groupfile.fa> for reading.

### ISSUE THREAD

**Issue by josmos** [ctSkennerton/crass#88]
Hi,

I am not sure wether this is a bug or I am getting something wrong.
I was running crass with standard parameters on fastq files, which worked.
However, if I try to assemble CRISPRS with 
`crass-assembler --velvet -g 24159 -s 23,158,189 -x crass.crispr -i .`
i get the following error: 

crass : [ERROR] Could not open FASTQ .Group_24159_CAAACTGAGTACCTTGAGGTTGCCCCCCAGGCA.fa for reading.

Thanks for your support,
Josef

**Comment by ctSkennerton** [comment]
Hi Josef,

could you try putting "./" as the argument to `-i`. I think this could be a silly bug where the directory and the file aren't getting joined properly and so the file name comes out as ".Group_24159_CAAACTGAGTACCTTGAGGTTGCCCCCCAGGCA.fa" rather than "./Group_24159_CAAACTGAGTACCTTGAGGTTGCCCCCCAGGCA.fa"

**Comment by josmos** [comment]
It worked!

I didn't think of that, thank you!
