### ISSUE TITLE
quick Q of Coverage and spid

### ISSUE THREAD

**Issue by Ruonan0101** [ctSkennerton/crass#91]
e.g. spacer cov="4" seq="GAGATTTGAAGTCACTACTCTT" spid="SP24" from 35 source reads
e.g. spacer cov="1" seq="AGCAGCGGAACAGCGGTAGTCGGCACAGGTACAAA" spid="SP242" from 1 source read'
1, how the spacer cov is calculated? does that mean how many times the full length of a certain spacer is found in the source reads? 
2, I found that the same spid is assigned to different sequences. So I want to know what are the criteria to assign the spid? 
Thanks. Looking forward to the reply.

**Comment by ctSkennerton** [comment]
The coverage is approximately how many times the spacer was identified in the metagenome. My memory is pretty fuzzy about spid but I think it's only guaranteed to be unique within the CRISPR. If you are finding different spacers within the same group with the same spid then it's a problem, otherwise I think it's fine. 

Sorry if these answers are a bit vague, it's been many years since Crass was written and I've forgotten many details of how things work under the hood.

**Comment by Ruonan0101** [comment]
I see. Thanks for the reply. I will check the spid carefully.
