### ISSUE TITLE
Crass compilation

### ISSUE THREAD

**Issue by 473021677** [ctSkennerton/crass#93]
Hi:
   I am trying to compile Crass but I have encountered one problem. When I am using the command "./configure" to compile Crass, it shows "checking for velvetg... no" and "checking for velveth... no". And after I have completed the installation and compilation, the program cann't run and report an error "crass [ERROR]: crass-assembler cannot use velvet. Please re-compile with velvet in you PATH" when I try to run crass-assembler using the command "crass-assembler --velvet". I don't know how to solve this problem. Would it be possible for you to help me? Thanks.

Sincerely,
Yuan

**Comment by ctSkennerton** [comment]
Hi Yuan,

You need to have at least [velvet](https://www.ebi.ac.uk/~zerbino/velvet/) installed on your system before you run configure to get `crass-assembler` to work. However, `crass-assembler` isn't required to find crispr spacers in datasets for that you should run the `crass` command, which doesn't require velvet to be installed. I would recommend just running `crass` and then using another assembler on the reads that are identified to assemble the CRISPR, since there are many better assemblers than `velvet` these days.

Cheers,
Connor

**Comment by 473021677** [comment]
Hi：
    Thanks for your reply very much. I have solved this problem. I will consider your advice about the assemblers' choice seriously. Thanks.

Sincerely,
Yuan
